kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-zookeeper-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zk-local-storege