## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
enabled: true
brokers: 1
image: harbor.k8s/ada/logkeeper-kafka
imageTag: 5.4.0
heapOptions: "-Xms512M -Xmx512M"
zookeeper:
  url: "10.8.4.75/logkeeper-kafka"
persistence:
  enabled: true
  storageClass: kafka-data-local-storege
  size: 5Gi
  disksPerBroker: 1
resources:
  limits:
   cpu: 100m
   memory: 1024Mi
  requests:
   cpu: 100m
   memory: 1024Mi
configurationOverrides:
  "offsets.topic.replication.factor": 1
  "confluent.license.topic.replication.factor": 1
  "confluent.metrics.reporter.topic.replicas": 1
  "default.replication.factor": 1
  "topic.replicas": 1
  "min.insync.replicas": 1
  "auto.create.topics.enable": true
  "num.partitions": 8
  "log.retention.hours": 48
  "auto.offset.reset": earliest
  "zookeeper.connection.timeout.ms": 12000
  "listener.security.protocol.map": |-
    PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
nodeport:
  enabled: false
  servicePort: 19092
  firstListenerPort: 31090
## 下面的配置请勿修改
imagePullPolicy: IfNotPresent
imagePullSecrets:
podManagementPolicy: OrderedReady
updateStrategy: RollingUpdate
customEnv: {}
podAnnotations: {}
nodeSelector: {}
tolerations: {}
jmx:
  port: 5555
prometheus:
  jmx:
    enabled: false
    image: solsson/kafka-prometheus-jmx-exporter@sha256
    imageTag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
    imagePullPolicy: IfNotPresent
    port: 5556
    resources: {}

