## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
cp-kafka:
  enabled: true
  brokers: 1
  image: harbor.k8s/ada/cp-enterprise-kafka
  imageTag: 5.4.0
  heapOptions: "-Xms512M -Xmx512M"
  persistence:
    enabled: true
    storageClass: kafka-data-local-storege
    size: 5Gi
    disksPerBroker: 1
  resources:
    limits:
     cpu: 100m
     memory: 1024Mi
    requests:
     cpu: 100m
     memory: 1024Mi
  configurationOverrides:
    "default.replication.factor": 1
    "num.partitions": 8
    "log.retention.hours": 48
    "auto.offset.reset": earliest

## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:  
  enabled: false
  servers: 1
  image: harbor.k8s/ada/cp-zookeeper
  imageTag: 5.4.0
  heapOptions: "-Xms512M -Xmx512M"
  persistence:
    enabled: true
    dataDirSize: 1Gi
    dataDirStorageClass: zk-data-local-storege
    dataLogDirSize: 1Gi
    dataLogDirStorageClass: zk-log-local-storege
  resources:
     limits:
      cpu: 100m
      memory: 128Mi
     requests:
      cpu: 100m
      memory: 128Mi
