apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-pv1
  namespace: miaozy
  labels:
    type: kafka
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: kafka-local-storege
  local:
    path: /mnt/pv/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 108443.server.bigdata.com.cn