apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-pv0
  namespace: kafka
  labels:
    type: kafka
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: kafka-data-local-storege
  local:
    path: /mnt/pv/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 108413.server.bigdata.com.cn