apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-log-pv2
  namespace: zookeeper
  labels:
    "type": "zookeeper"
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: zk-log-local-storege
  local:
    path: /mnt/pv/zookeeper/log
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 108473.server.bigdata.com.cn